title: Kik Bot - Python
description: FALL'18 COMP3220(2), Project-4, Auburn University. {Instructor - Dr. Li, TA - Jay Patel(jsp0053@auburn.edu)}
show_downloads: false
google_analytics: false
theme: jekyll-theme-cayman